### ISSUE TITLE
Add info on #: a special symbol for hsc files

### ISSUE THREAD

**Issue by maurges** [takenobu-hs/haskell-symbol-search-cheatsheet#4]
This can cite [the documentation](https://downloads.haskell.org/ghc/latest/docs/html/users_guide/utils.html#input-syntax)
This should also mention the `#{command args, args}` syntax, it was this syntax that brought me here.
Even though it's not __really__ haskell, hsc2hs is a tool that is transparently run by cabal, so someone might be confused by it (as I was).

**Comment by takenobu-hs** [comment]
@d86leader, I'll add this. Thanks!

**Comment by takenobu-hs** [comment]
Added, thanks.
